name: Auto Update B-DNS APK

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  download-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download APK and Rename
        run: |
          URL="https://drive.usercontent.google.com/download?id=1JKcBa0WQ-PoGTdwHaLEV1TnusMSJKtKI&export=download&authuser=0&confirm=t&uuid=037e43c3-bdba-4324-8242-55e9ccd91650&at=AMrWOn3CqiinfWKtpIvAw3bAK4Yg%3A1788659754218"
          FILENAME="B-DNS-9243236.apk"
          
          curl -sSLk -f -o "$FILENAME" "$URL"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          FILENAME="B-DNS-9243236.apk"
          git add "$FILENAME"
          
          if git status --porcelain | grep -q .; then
            git commit -m "Auto update SmartTube APK [$(date +'%Y-%m-%d')]"
            git push
          else
            echo "File APK không có sự thay đổi mới."
          fi
