name: Auto Update CocCoc APK

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  download-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download APK and Rename
        run: |
          URL="https://tinhlagi.pro/app/?download=fb960a292f1e39d08ff2ca0278b6fd048aefe72387666b197079b638eec415d3"
          FILENAME="Cốc Cốc-2410701.apk"
          
          curl -sSLk -f -o "$FILENAME" "$URL"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          FILENAME="Cốc Cốc-2410701.apk"
          git add "$FILENAME"
          
          if git status --porcelain | grep -q .; then
            git commit -m "Auto update SmartTube APK [$(date +'%Y-%m-%d')]"
            git push
          else
            echo "File APK không có sự thay đổi mới."
          fi
