name: Auto Update DLStore APK

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  download-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download APK and Rename
        run: |
          URL="https://download2330.mediafire.com/tdawordlunugtE-XbEzSG7rE8CKVUM_DIpcWBHKz-lZ4ieD5EHtEPKQR5FZ_0or124KDH0LGGtJZlv82c-3kKxcsrutkqRO5Q8MCR41_hJAZcAcJYG55t2Er52pCZ2Al_0QFKL7rccWB_wRNyG3oIqB3qlkort6FyRkoTaFp6k62GPI/jeec7t5kbwsqz9e/DLStore_v16.0.5.apk"
          FILENAME="DLStore-3199886.apk"
          
          curl -sSLk -f -o "$FILENAME" "$URL"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          FILENAME="DLStore-3199886.apk"
          git add "$FILENAME"
          
          if git status --porcelain | grep -q .; then
            git commit -m "Auto update SmartTube APK [$(date +'%Y-%m-%d')]"
            git push
          else
            echo "File APK không có sự thay đổi mới."
          fi
