name: Auto Update MCU Store APK

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  download-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download APK and Rename
        run: |
          URL="https://tinhlagi.pro/app/?download=ce5bec21483aabc3884e81555f626c384ab14fd5c2d7e6f85170c85bfe3b9e63"
          FILENAME="MCUStore-5626005.apk"
          
          curl -sSLk -f -o "$FILENAME" "$URL"

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          FILENAME="MCUStore-5626005.apk"
          git add "$FILENAME"
          
          if git status --porcelain | grep -q .; then
            git commit -m "Auto update SmartTube APK [$(date +'%Y-%m-%d')]"
            git push
          else
            echo "File APK không có sự thay đổi mới."
          fi
